spring:
  datasource:
    url: jdbc:mysql://${cn.sh.lz.cloud.mysql.host}:${cn.sh.lz.cloud.mysql.port}/${cn.sh.lz.cloud.mysql.database}?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
#    show-sql: true
  jackson:
    default-property-inclusion: non_null
cn:
  sh:
    lz:
      cloud:
        mysql:
          host: ${mysql-host:127.0.0.1}
          port: ${mysql-port:3306}
          database: ${mysql-database:home}
#logging:
#  level:
#    org.hibernate.type: TRACE
